# This is a basic workflow to help you get started with Actions

name: passing job values

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  pass_in_one_job:
    outputs:
      COLOR: $COLOR
    runs-on: ubuntu-latest
    steps:
      - name: Set color
        id: color-selector
        run: |
          COLOR=blue
      - name: Get color
        run: echo "The selected color is $COLOR"
 
        
  producer:
    runs-on: ubuntu-latest
    needs: pass_in_one_job
    steps:
      - name: Make a sentence
        id: sentence_maker
        env:
          COLOREK: ${{ steps.pass_in_one_job.outputs.color-selector.COLOR }}
        run: |
            echo "The selected color is $COLOREK"
            echo "message='The selected color is $COLOREK'" >>> $GITHUB_OUTPUT
  consumer:
    runs-on: ubuntu-latest
    steps:
      - name: Print the message
        run: |
          echo $message

  job_1:
    name: Add 3 and 7
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          expr 3 + 7 > hakuna_matata.txt
      - name: artefakt
        uses: actions/upload-artifact@v2
        with:
          name: hakuna_matata
          path: hakuna_matata.txt
  job_2:
    name: Multiply by 9
    needs: job_1
    runs-on: windows-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: hakuna_matata
      - shell: bash
        run: |
          value=`cat hakuna_matata.txt`
          echo $(expr $value \* 9) 